 // BUNDLERS: ES UN PROGRAMA QUE AGRUPA MUCHOS ARCHIVO EN UNO.(webpack)
 // TRANSPILADORES: ES UN PROGRAMA QUE TRADUCE UN LENGUAJE DE PROGRAMACION A OTRO. (A JS VANILLA (babel)) 
 // JSX: ES UNA FORMA DE ESCRIBIR (JS) QUE NO SE PUEDE USAR EN (HTML)
 // CREATE-REACT-APP: ES UNA HERRAMIENTA QUE TE PERMITE CREAR UNA APLICACION DE REACT.
 

 